// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS0OohgKZQo3gqcNEXdAVCHgYC8OqWeqE',
    appId: '1:239016585741:web:464b2e9e9cce5cf9b4c344',
    messagingSenderId: '239016585741',
    projectId: 'aldaleeel-9d2e4',
    authDomain: 'aldaleeel-9d2e4.firebaseapp.com',
    storageBucket: 'aldaleeel-9d2e4.firebasestorage.app',
    measurementId: 'G-7TP4QR1XT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DZ1P3S75yMMac7vEuHf6C2ToOSpU0Xk',
    appId: '1:239016585741:android:cf6bd1c72aceac86b4c344',
    messagingSenderId: '239016585741',
    projectId: 'aldaleeel-9d2e4',
    storageBucket: 'aldaleeel-9d2e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dS9_LZQTmWWAcAZS5d8bPj4RhRDeW5E',
    appId: '1:239016585741:ios:658fb13386cad724b4c344',
    messagingSenderId: '239016585741',
    projectId: 'aldaleeel-9d2e4',
    storageBucket: 'aldaleeel-9d2e4.firebasestorage.app',
    iosBundleId: 'com.project.flutterFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7dS9_LZQTmWWAcAZS5d8bPj4RhRDeW5E',
    appId: '1:239016585741:ios:658fb13386cad724b4c344',
    messagingSenderId: '239016585741',
    projectId: 'aldaleeel-9d2e4',
    storageBucket: 'aldaleeel-9d2e4.firebasestorage.app',
    iosBundleId: 'com.project.flutterFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS0OohgKZQo3gqcNEXdAVCHgYC8OqWeqE',
    appId: '1:239016585741:web:a347cf7077a78cc4b4c344',
    messagingSenderId: '239016585741',
    projectId: 'aldaleeel-9d2e4',
    authDomain: 'aldaleeel-9d2e4.firebaseapp.com',
    storageBucket: 'aldaleeel-9d2e4.firebasestorage.app',
    measurementId: 'G-CX1YJR17EM',
  );

}